DATA_DIR: /home/yxue/datasets
RNG_SEED: 3407
MODEL:
  ADAPTATION: source
  ARCH: Standard_R50
TEST:
  BATCH_SIZE: 32
CORRUPTION:
  DATASET: imagenet
  SEVERITY:
    - 1
  TYPE:
    # - gaussian_noise
    # - shot_noise
    # - impulse_noise
    # - defocus_blur
    # - glass_blur
    # - motion_blur
    # - zoom_blur
    # - snow
    # - frost
    # - fog
    # - brightness
    # - contrast
    # - elastic_transform
    # - pixelate
    - jpeg_compression
OPTIM:
  METHOD: SGD
  LR: 0.001
  MOMENTUM: 0.9
  WD: 5e-4
