DATA_DIR: /home/yxue/datasets
CKPT_DIR: /home/yxue/model_fusion_tta/cifar/ckpt
MODEL:
  ADAPTATION: source
  ARCH: Standard
TEST:
  BATCH_SIZE: 32
CORRUPTION:
  DATASET: cifar10
  SEVERITY:
    - 5
  TYPE:
    # - gaussian_noise
    # - shot_noise
    # - impulse_noise
    # - defocus_blur
    # - glass_blur
    # - motion_blur
    # - zoom_blur
    # - snow
    # - frost
    # - fog
    # - brightness
    # - contrast
    # - elastic_transform
    - pixelate
    # - jpeg_compression
