DATA_DIR: /home/yxue/datasets
MODEL:
  ADAPTATION: source
  ARCH: Hendrycks2020AugMix_ResNeXt
TEST:
  BATCH_SIZE: 32
CORRUPTION:
  DATASET: cifar100
  SEVERITY:
    - 5
  TYPE:
    # - gaussian_noise
    # - shot_noise
    # - impulse_noise
    # - defocus_blur
    # - glass_blur
    # - motion_blur
    - zoom_blur
    # - snow
    # - frost
    # - fog
    # - brightness
    # - contrast
    # - elastic_transform
    # - pixelate
    # - jpeg_compression
OPTIM:
  METHOD: SGD
  LR: 0.001
  MOMENTUM: 0.9
  WD: 5e-4
